services:
  app:
    entrypoint:
    - pip install -e .[dev]
    - sleep
    - infinity
    image: allrisc/pydocker:latest
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

